import Head from "next/head";
import { useState } from "react";
import { BsFillMoonStarsFill, BsFillSunFill } from "react-icons/bs";
import { AiFillGithub, AiFillLinkedin, AiFillInstagram } from "react-icons/ai";
import Image from "next/image";
import { motion } from "framer-motion";
import { avatar, vite, postgre, redux, tanstack } from "@public/images";
import { ServiceSection } from "components/Services";
import { ExperienceTimeline } from "@components/Timeline";
import ProjectSection from "@components/Projects";

const Home = () => {
  const [darkMode, setDarkMode] = useState(true);
  return (
    <motion.div
      className={darkMode ? "dark" : ""}
      initial={{ y: "100vw" }}
      animate={{ y: 0 }}
      transition={{ type: "spring", delay: 0.4 }}
    >
      <Head>
        <title>Chandra Septian - Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <main className="bg-second-light dark:bg-primary-dark">
        <section>
          <nav className="px-12 py-8 flex justify-between">
            <h1 className="text-2xl font-tomorrow text-primary-dark dark:text-second-light">
              CSeptian
            </h1>
            <ul className="flex items-center">
              <li>
                {darkMode ? (
                  <BsFillSunFill
                    onClick={() => setDarkMode(!darkMode)}
                    className="cursor-pointer text-2xl dark:text-yellow-400"
                  />
                ) : (
                  <BsFillMoonStarsFill
                    onClick={() => setDarkMode(!darkMode)}
                    className="cursor-pointer text-2xl text-yellow-400"
                  />
                )}
              </li>
            </ul>
          </nav>
          <div className="px-12 flex gap-4 my-10">
            <div className="w-[30%]">
              <div
                className="relative rounded-full w-40 h-40 overflow-hidden md:h-48 md:w-48 bg-primary-light dark:bg-second-light">
                <Image alt="avatar" src={avatar} fill />
              </div>
              <h2
                className="font-tomorrow text-xl my-4 md:text-l text-primary-dark dark:text-second-light"
              >
                Hello! I`m Chandra Septian
              </h2>
              <h3 className="font-tomorrow text-xl md:text-l text-primary-dark dark:text-second-light">
                Senior Software Engineer 🇮🇩
              </h3>
            </div>
            <div className="w-[70%] flex items-center justify-center">
              <p className="font-mono text-l md:text-xl max-w-3xl text-primary-dark dark:text-second-light">
                A young competent and professional software engineer with 5+ years experience on software
                development. Well-organized, hard-worker, and willing to learn more. Working well in both individual and
                team, with excellent self-awareness and communication skills.
              </p>
            </div>
          </div>
          <div className="flex justify-center gap-16 py-4 text-4xl text-second-light bg-primary-light dark:text-primary-dark dark:bg-second-light">
            <AiFillGithub
              className="cursor-pointer "
              onClick={() => window.open("https://www.github.com", "_blank")}
            />
            <AiFillLinkedin
              className="cursor-pointer"
              onClick={() =>
                window.open("https://www.linkedin.com/in/cseptian/", "_blank")
              }
            />
            <AiFillInstagram
              className="cursor-pointer"
              onClick={() => window.open("https://www.instagram.com", "_blank")}
            />
          </div>
        </section>
        <ServiceSection />
        <ProjectSection />
        <ExperienceTimeline />
        <section>
          <div className="flex justify-center my-10">
            <h3 className="text-4xl font-bold font-tomorrow text-primary-dark dark:text-second-light">
              Technology
            </h3>
          </div>
          <div className="flex justify-evenly py-6 px-12 bg-primary-light dark:bg-second-light">
            <Image alt="vite" src={vite} width={120} height={120} />
            <Image alt="postgre" src={postgre} width={120} height={120} />
            <Image alt="tanstack" src={tanstack} width={120} height={120} />
            <Image alt="redux" src={redux} width={120} height={120} />
          </div>
        </section>
      </main>
    </motion.div>
  );
};

export default Home;
