import Head from "next/head";
import { useState } from "react";
import { BsFillMoonStarsFill, BsFillSunFill } from "react-icons/bs";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillInstagram,
} from "react-icons/ai";
import Image from "next/image";
import avatar from "../public/avatar.png";
import design from "../public/design.png";
import code from "../public/code.png";
import consulting from "../public/consulting.png";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";

const Home = () => {
  const [darkMode, setDarkMode] = useState(true);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Chandra Septian - Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-slate-800">
        <section className="min-h-screen">
          <nav className="py-10 mb-4 flex justify-between">
            <h1 className="text-2xl font-burtons text-teal-600 dark:text-sky-400">
              CSeptian
            </h1>
            <ul className="flex items-center">
              <li>
                {darkMode ? (
                  <BsFillSunFill
                    onClick={() => setDarkMode(!darkMode)}
                    className="cursor-pointer text-2xl dark:text-yellow-400"
                  />
                ) : (
                  <BsFillMoonStarsFill
                    onClick={() => setDarkMode(!darkMode)}
                    className="cursor-pointer text-2xl"
                  />
                )}
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 to-teal-400 text-white px-4 py-2 rounded-md ml-8 dark:bg-gradient-to-br dark:from-sky-900 dark:to-sky-600"
                  href="#portfolio"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className="text-6xl py-2 font-medium md:text-6xl text-transparent bg-clip-text bg-gradient-to-b from-teal-700 to-emerald-400 dark:bg-gradient-to-b dark:from-teal-300 dark:to-sky-500">
              Chandra Septian
            </h2>
            <h3 className="text-2xl py-2 md:text-3xl dark:text-slate-100">
              Developer and Engineer
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 md:text-xl max-w-2xl mx-auto dark:text-slate-100">
              A young competent and professional software engineer. Be able to
              work in the public and private sectors. Well-organized,
              hard-working, and willing to learn more. Working well in both
              individual and team, with excellent self-awareness and
              communication skills. In addition, I have several programming
              training certifications and quite active in several developer
              communities in Bandung.
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-slate-100">
            <AiFillTwitterCircle
              className="cursor-pointer"
              onClick={() => window.open("https://www.twitter.com", "_blank")}
            />
            <AiFillLinkedin
              className="cursor-pointer"
              onClick={() => window.open("https://www.linkedin.com/in/cseptian/", "_blank")}
            />
            <AiFillInstagram
              className="cursor-pointer"
              onClick={() => window.open("https://www.instagram.com", "_blank")}
            />
          </div>
          <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96 dark:bg-gradient-to-b dark:from-sky-300 dark:to-sky-700">
            <Image alt="avatar" src={avatar} layout="fill" objectFit="cover" />
          </div>
        </section>

        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-slate-100">
              Services I Offer
            </h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-slate-100">
              Since the beginning of my journey as a frontend developer, I`ve
              done work for{" "}
              <span className="text-sky-700 font-bold dark:text-sky-400">
                Dicoding
              </span>{" "}
              as an{" "}
              <span className="text-sky-700 font-bold dark:text-sky-400">
                External Code Reviewer
              </span>{" "}
              and collaborated with talented people in my current job at{" "}
              <span className="text-yellow-500 font-bold">
                PT United Tracktors Tbk
              </span>{" "}
              to create an application for maintenance management for heavy
              equipment such as excavators.
            </p>
            <p>ABCD</p>
          </div>
          <div className="lg:flex gap-12">
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-slate-300">
              <Image
                alt="design"
                className="mx-auto"
                src={design}
                width={100}
                height={100}
              />
              <h3 className="text-lg font-medium pt-8 pb-2">
                Beautiful Designs
              </h3>
              <p className="py-2">
                Creating elegant designs suited for your needs design theory
              </p>
              <h4 className="py-4 text-teal-600">Design tools I use</h4>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Illustrator</p>
              <p className="text-gray-800 py-1">Figma</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-slate-300">
              <Image
                alt="code"
                className="mx-auto"
                src={code}
                width={100}
                height={100}
              />
              <h3 className="text-lg font-medium pt-8 pb-2">
                Beautiful Designs
              </h3>
              <p className="py-2">
                Creating elegant designs suited for your needs design theory
              </p>
              <h4 className="py-4 text-teal-600">Design tools I use</h4>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Illustrator</p>
              <p className="text-gray-800 py-1">Figma</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-slate-300">
              <Image
                alt="consulting"
                className="mx-auto"
                src={consulting}
                width={100}
                height={100}
              />
              <h3 className="text-lg font-medium pt-8 pb-2">
                Beautiful Designs
              </h3>
              <p className="py-2">
                Creating elegant designs suited for your needs design theory
              </p>
              <h4 className="py-4 text-teal-600">Design tools I use</h4>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Illustrator</p>
              <p className="text-gray-800 py-1">Figma</p>
            </div>
          </div>
        </section>
        <section>
          <div id="portfolio">
            <h3 className="text-3xl py-1 dark:text-slate-100">Portfolio</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-slate-100">
              Since the beginning of my journey as a frontend developer, I`ve
              done work for{" "}
              <span className="text-sky-700 font-bold">Dicoding</span> as an{" "}
              <span className="text-sky-700 font-bold">
                External Code Reviewer
              </span>{" "}
              and collaborated with talented people in my current job at{" "}
              <span className="text-yellow-500 font-bold">
                PT United Tracktors Tbk
              </span>{" "}
              to create an application for maintenance management for heavy
              equipment such as excavators.
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1">
              <Image
                alt="web1"
                src={web1}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                alt="web1"
                src={web2}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                alt="web1"
                src={web3}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                alt="web1"
                src={web4}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                alt="web1"
                src={web5}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                alt="web1"
                src={web6}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
          </div>
        </section>
      </main>
    </div>
  );
};

export default Home;
