import Head from "next/head";
import { useState } from "react";
import { BsFillMoonStarsFill, BsFillSunFill } from "react-icons/bs";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillInstagram,
} from "react-icons/ai";
import Image from "next/image";
import { motion } from "framer-motion";
import avatar from "../public/avatar.png";
import { ServiceCard } from "../components/services/services-card";
import { PortfolioCard } from "../components/portfolio/portfolio-card";
import { Timeline } from "../components/timeline/timeline";

const Home = () => {
  const [darkMode, setDarkMode] = useState(true);
  return (
    <motion.div
      className={darkMode ? "dark" : ""}
      initial={{ y: "100vw" }}
      animate={{ y: 0 }}
      transition={{ type: "spring", delay: 0.4 }}
    >
      <Head>
        <title>Chandra Septian - Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <main className="bg-primary-light px-10 md:px-20 lg:px-35 dark:bg-primary-dark">
        <section className="min-h-screen">
          <nav className="py-10 mb-4 flex justify-between">
            <h1 className="text-2xl font-burtons text-transparent bg-clip-text gradient-color">
              CSeptian
            </h1>
            <ul className="flex items-center">
              <li>
                {darkMode ? (
                  <BsFillSunFill
                    onClick={() => setDarkMode(!darkMode)}
                    className="cursor-pointer text-2xl dark:text-yellow-400"
                  />
                ) : (
                  <BsFillMoonStarsFill
                    onClick={() => setDarkMode(!darkMode)}
                    className="cursor-pointer text-2xl text-yellow-400"
                  />
                )}
              </li>
            </ul>
          </nav>
          <div className="text-center p-8">
            <motion.h2
              className="font-burtons text-6xl py-5 font-medium md:text-6xl text-transparent bg-clip-text gradient-color"
              whileHover={{ scale: 1.1 }}
              transition={{ type: "spring", stiffness: 300 }}
            >
              Chandra Septian
            </motion.h2>
            <h3 className="font-mono text-2xl py-5 md:text-3xl text-color">
              Developer and Engineer
            </h3>
            <p className="font-mono text-md py-4 leading-8 md:text-xl max-w-3xl mx-auto text-color">
              A young competent and professional software engineer. Be able to
              work in the public and private sectors. Well-organized,
              hard-working, and willing to learn more. Working well in both
              individual and team, with excellent self-awareness and
              communication skills. In addition, I have several programming
              training certifications and quite active in several developer
              communities in Bandung.
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 text-color">
            <AiFillTwitterCircle
              className="cursor-pointer"
              onClick={() => window.open("https://www.twitter.com", "_blank")}
            />
            <AiFillLinkedin
              className="cursor-pointer"
              onClick={() =>
                window.open("https://www.linkedin.com/in/cseptian/", "_blank")
              }
            />
            <AiFillInstagram
              className="cursor-pointer"
              onClick={() => window.open("https://www.instagram.com", "_blank")}
            />
          </div>
          <div className="relative mx-auto rounded-full w-80 h-80 mt-10 mb-10 overflow-hidden md:h-96 md:w-96 gradient-color">
            <Image alt="avatar" src={avatar} fill />
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 font-bold font-burtons text-transparent bg-clip-text gradient-color">
              Services
            </h3>
            <p className="text-md py-2 leading-8 text-color">
              Since the beginning of my journey as a frontend developer, I have
              done work for{" "}
              <span className="text-sky-700 font-bold dark:text-sky-300">
                Dicoding
              </span>{" "}
              as an{" "}
              <span className="text-sky-700 font-bold dark:text-sky-300">
                External Code Reviewer
              </span>{" "}
              and collaborated with talented people in my current job at{" "}
              <span className="text-yellow-500 font-bold">
                PT United Tractors Tbk
              </span>{" "}
              to create an application for maintaining management of heavy
              equipment such as excavators.
            </p>
          </div>
          <ServiceCard />
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 font-bold font-burtons text-transparent bg-clip-text gradient-color">
              Experiences
            </h3>
            <Timeline />
          </div>
        </section>
        <section>
          <div id="portfolio">
            <h3 className="text-3xl py-1 font-bold font-burtons text-transparent bg-clip-text gradient-color">
              Portfolio
            </h3>
            <p className="text-md py-2 leading-8 text-color">
              Here are some examples of projects that I have made while being a
              frontend developer. Some of them are web and mobile projects.
              Besides that, I also studied and created a build pipeline using
              azure devops.
            </p>
            <PortfolioCard />
          </div>
        </section>
      </main>
    </motion.div>
  );
};

export default Home;
